swagger: '2.0'
info:
  description: Asset DB ドキュメント
  version: 0.0.1
  title: Asset DB REST APIs
#host: localhost:8080
basePath: /api/db
tags:
  - name: facilities
    description: Facilities APIs
  - name: snapshots
    description: Snapshots APIs
schemes:
  - http
  - https
paths:
  /create_facility:
    post:
      tags:
        - facilities
      summary: Facility 作成
      description: Facility 作成
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/FacilityRequest'
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /read_facility/{facility_id}:
    get:
      tags:
        - facilities
      summary: Facility 取得
      description: Facility 取得
      produces:
        - application/json
      parameters:
        - name: facility_id
          type: string
          in: path
          description: Asset ID
          required: true
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /read_facilities:
    get:
      tags:
        - facilities
      summary: Facilities 全取得
      description: Facilities 全取得
      produces:
        - application/json
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /plus_asset:
    post:
      tags:
        - facilities
      summary: Asset 補給
      description: Asset 補給
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/FacilityRequest'
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /minus_asset:
    post:
      tags:
        - facilities
      summary: Asset 減少
      description: Asset 減少
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/FacilityRequest'
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /consume_asset_percent/{facility_id}:
    post:
      tags:
        - facilities
      summary: Asset 利用
      description: Asset 利用
      produces:
        - application/json
      parameters:
        - name: facility_id
          type: string
          in: path
          description: Facility ID
          required: true
        - name: body
          in: body
          schema:
            $ref: '#/definitions/PercentRequest'
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /consume_asset_amount/{facility_id}:
    post:
      tags:
        - facilities
      summary: Asset 利用
      description: Asset 利用
      produces:
        - application/json
      parameters:
        - name: facility_id
          type: string
          in: path
          description: Facility ID
          required: true
        - name: body
          in: body
          schema:
            $ref: '#/definitions/AmountRequest'
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /transport_asset/{facility_id_from}/{facility_id_to}:
    post:
      tags:
        - facilities
      summary: Asset 移動
      description: Asset 移動
      produces:
        - application/json
      parameters:
        - name: facility_id_from
          type: string
          in: path
          description: 移動元 Facility ID
          required: true
        - name: facility_id_to
          type: string
          in: path
          description: 移動先 Facility ID
          required: true
        - name: body
          in: body
          schema:
            $ref: '#/definitions/AmountRequest'
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /reset_falicity/{falicity_id}:
    post:
      tags:
        - facilities
      summary: Facility リセット
      description: Facility リセット
      produces:
        - application/json
      parameters:
        - name: facility_id
          type: string
          in: path
          description: Facility ID
          required: true
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /reset_facilities:
    post:
      tags:
        - facilities
      summary: Facility 全リセット
      description: Facility 全リセット
      produces:
        - application/json
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /remove_facility/{facility_id}:
    delete:
      tags:
        - facilities
      summary: Facility 削除
      description: Facility 削除
      produces:
        - application/json
      parameters:
        - name: facility_id
          type: string
          in: path
          description: Facility ID
          required: true
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /remove_facilities:
    delete:
      tags:
        - facilities
      summary: Facility 全削除
      description: Facility 全削除
      produces:
        - application/json
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /read_snapshots:
    get:
      tags:
        - snapshots
      summary: Snapshot 全取得
      description: Snapshot 全取得
      produces:
        - application/json
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /remove_snapshots:
    delete:
      tags:
        - snapshots
      summary: Snapshot 全削除
      description: Snapshot 全削除
      produces:
        - application/json
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
definitions:
  FacilityRequest:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      asset_a_name:
        type: string
      asset_a_num:
        type: number
      asset_b_name:
        type: string
      asset_b_num:
        type: number
      asset_max:
        type: number
  PercentRequest:
    type: object
    properties:
      percent:
        type: number
  AmountRequest:
    type: object
    properties:
      amount:
        type: number

